name: CI

on:
  push:
    paths:
      - ".github/workflows/ci.yaml"
      - "src/**"
      - "test/**"
    tags-ignore:
      - "**"
    branches:
      - "**"

jobs:
  bundle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: bundle
        run: npx @redocly/cli@latest bundle --config redocly/redocly.yaml src/openapi.yaml -o openapi.yaml
      - name: lint
        run: npx @redocly/cli@latest lint --config redocly/redocly.yaml openapi.yaml
      - uses: actions/upload-artifact@v4
        with:
          name: openapi
          path: openapi.yaml

  generate_openapi-typescript:
    needs: bundle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - uses: actions/download-artifact@v4
        with:
          name: openapi
      - name: generate type file
        run: npx openapi-typescript@latest openapi.yaml -o test/dist/openapi-typescript/schema.d.ts
      - uses: actions/upload-artifact@v4
        with:
          name: schema
          path: test/dist/openapi-typescript/schema.d.ts

  integration-test:
    needs: generate_openapi-typescript
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: openapi
      - uses: actions/download-artifact@v4
        with:
          name: schema
          path: test/dist/openapi-typescript
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: "test/package-lock.json"
      - run: |
          npm ci
          ./run-test.sh
        working-directory: test
        env:
          OPENAPI_PATH: ${{ github.workspace }}/openapi.yaml
          SCHEMA_PATH: ${{ github.workspace }}/test/dist/openapi-typescript/schema.d.ts

  commit:
    needs: integration-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: openapi
      - name: commit & push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add openapi.yaml
          git diff-index --quiet HEAD openapi.yaml || (git commit -m "Update bundled file" && git push)
